name: MacOS Workflow
on:
  push:
    paths-ignore:
      - '**/**.md'
    branches:
      - main
      - adding_bubbles
      - add-map-method
      - method_to_return_bubble_for_snapshot
  pull_request:
    branches:
      - main

jobs:
  run_test:
    name: running test functions on macos
    runs-on: macos-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Checkout
        uses: actions/checkout@v1
    
      - name: install cocoapods
        run: sudo gem install cocoapods
        
      - name: install xcodeproj
        run: sudo gem install xcodeproj
        
      - name: pip upgrade
        run: sudo pip install --upgrade pip
        
      - name: install matplotlib
        run: pip install --user --upgrade matplotlib
        
      - name: install six
        run: pip install six
      
      - name: install nativescript
        run: npm install -g nativescript

      - name: tns build
        run: tns build ios
        working-directory: appGeo/

      - name: tns test build
        run: tns test init --framework qunit
        working-directory: appGeo/
      
      - name: tns test run  
        run: tns test ios --justlaunch
        working-directory: appGeo/

  build_app:
    name: building app and launching on macos
    runs-on: macos-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Checkout
        uses: actions/checkout@v1
    
      - name: install cocoapods
        run: sudo gem install cocoapods
        
      - name: install xcodeproj
        run: sudo gem install xcodeproj
        
      - name: pip upgrade
        run: sudo pip install --upgrade pip
        
      - name: install matplotlib
        run: pip install --user --upgrade matplotlib
        
      - name: install six
        run: pip install six
      
      - name: install nativescript
        run: npm install -g nativescript

      - name: tns build ios
        run: tns build ios
        working-directory: appGeo/
        
      - name: view devices
        run: xcrun simctl list devices
        
      - name: tns run ios
        run: tns run ios --justlaunch
        working-directory: appGeo/

  release_app:
    name: building and releasing
    runs-on: macos-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Checkout
        uses: actions/checkout@v1
    
      - name: install cocoapods
        run: sudo gem install cocoapods
        
      - name: install xcodeproj
        run: sudo gem install xcodeproj
        
      - name: pip upgrade
        run: sudo pip install --upgrade pip
        
      - name: install matplotlib
        run: pip install --user --upgrade matplotlib
        
      - name: install six
        run: pip install six
      
      - name: install nativescript
        run: npm install -g nativescript

      - name: build ipa file
        run: tns build ios --release --for-device
        working-directory: appGeo/
        
      - name: view file
        run: ls
        working-directory: appGeo/

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: appGeo/platforms/ios/build/Debug-iphonesimulator/appGeo.app
          asset_name: Most Recent Built .ipa Release for GeoMafia App
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is the most recent built .ipa release for GeoMafia app. To check how to import the app and run it on your iOS device, please check README"
