name: MacOS Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ios_build_test:
    name: build test on macos
    runs-on: macos-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Checkout
        uses: actions/checkout@v1
      
      - name: brew update
        run: brew update
      
      - name: Install node
        run: brew install node
    
      - name: install cocoapods
        run: sudo gem install cocoapods
        
      - name: install xcodeproj
        run: sudo gem install xcodeproj
        
      - name: pip upgrade
        run: sudo pip install --upgrade pip
        
      - name: install matplotlib
        run: pip install --user --upgrade matplotlib
        
      - name: install six
        run: pip install six
      
      - name: install nativescript
        run: npm install -g nativescript
      
      - name: tns build
        run: tns build ios
        working-directory: appGeo/
      
      - name: tns test build
        run: tns test init --framework qunit
        working-directory: appGeo/
      
      - name: tns test run
        run: tns test ios --justlaunch
        working-directory: appGeo/
