name: MacOS Workflow
on:
  push:
    branches:
      - workflow
  #pull_request:
   # branches:
    #  - main

jobs:
  ios_build_test:
    name: build test on macos
    runs-on: macos-latest

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Checkout
        uses: actions/checkout@v1
      
      - name: brew update
        run: brew update
      
      - name: Install node
        run: brew install node
    
      - name: install cocoapods
        run: sudo gem install cocoapods
        
      - name: install xcodeproj
        run: sudo gem install xcodeproj
        
      - name: pip upgrade
        run: sudo pip install --upgrade pip
        
      - name: install matplotlib
        run: pip install --user --upgrade matplotlib
        
      - name: install six
        run: pip install six
      
      - name: install nativescript
        run: npm install -g nativescript
        
      - name: test prepare
        run: tns prepare ios
        working-directory: appGeo/
      
      - name: check
        run: cat Podfile
        working-directory: appGeo/platforms/ios/
      
      - name: tns build
        run: tns build ios
        working-directory: appGeo/
